
platform :ios, '11.0'

#source 'ssh://git@10.10.10.105:7999/ios/raydataprivatepods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'test0' do
  	use_frameworks!

	#pod 'Kingfisher', '4.8.1'
	#pod 'SnapKit', '~> 4.0.0'
	#pod 'Moya', '~> 12.0.1'
	#pod 'Alamofire', '4.8.2'
	#pod 'ObjectMapper', '3.4.2'
 
  
end
